version: 2.1

jobs:
  main:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo pip install tox codecov
      - run: tox -e coverage
      - run: codecov
  py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: suo pip install tox
      - run: tox -e py38

workflows:
  main:
    jobs:
      - main
      - py38:
          requires:
            - main
